name: Verify Terraform Modules

on:
  push:
    branches:
      - feature
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        with:
          version: 1.1.7

      - name: Terraform Validate
        run: |
          find ./ -type f -name "*.tf" -exec terraform validate {} \;
