name: Verify Terraform Modules

on:
  push:
    branches:
      - feature
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        with:
          version: 1.1.7

      - name: Terraform Validate
        run: |
          for dir in $(find . -type d -path '*/modules/*'); do
            echo "Validating $dir"
            terraform validate $dir
          done
